export const ROLE = {
    ROLE_SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
    ROLE_ADMIN: 'ROLE_ADMIN',
    ROLE_TA_ADMIN: 'ROLE_TA_ADMIN',
    ROLE_TA: 'ROLE_TA',
    ROLE_HIRING_MANAGER: 'ROLE_HIRING_MANAGER',
    ROLE_OFCCEO_ADMIN: 'ROLE_OFCCEO_ADMIN'
}