const RECORD = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
};

const SHORTLIST_RESULT = {
    PASSED: 'PASSED',
    FAILED: 'FAILED'
};

const INTERVIEW_RESULT = {
    PASSED: 'PASSED',
    FAILED: 'FAILED'
};

const CANDIDATE = {
    PENDING: 'PENDING',
    CV_REVIEWED: 'CV_REVIEWED',
    IN_INTERVIEW: 'IN_INTERVIEW',
    IN_ASSESSMENT: 'IN_ASSESSMENT',
    HIRED: 'HIRED'
};

export const STATUS = {
    RECORD,
    SHORTLIST_RESULT,
    INTERVIEW_RESULT,
    CANDIDATE
};
