import { object, any, string, number } from "zod";

const Hire = object({
    id: any().optional().nullable(),
    candidateId: any().optional().nullable(),
    interviewId: any().optional().nullable(),
    candidateName: string().optional().nullable(),
    applicationCode: string().optional().nullable(),
    applicationDate: any().optional().nullable(),
    applicationPrefix: string().optional().nullable(),
    applicationNumber: any().optional().nullable(),
    departmentId: number().optional().nullable(),
    departmentName: string().optional().nullable(),
    headDepartmentId: number().optional().nullable(),
    headDepartmentName: string().optional().nullable(),
    offerPositionId: number().optional().nullable(),
    offerPositionName: string().optional().nullable(),
    offerLocationId: number().optional().nullable(),
    offerLocationName: string().optional().nullable(),
    businessDivisionId: number().optional().nullable(),
    businessDivisionName: string().optional().nullable(),
    offerSalary: any().optional().nullable(),
    offerDate: any().optional().nullable(),
    offerWeek: any().optional().nullable(),
    offerMonth: any().optional().nullable(),
    submitOPSOfficeDate: any().optional().nullable(),
    submitCEOOfficeDate: any().optional().nullable(),
    receivedOPSOfficeDate: any().optional().nullable(),
    receivedCEOOfficeDate: any().optional().nullable(),
    signedOfferDate: any().optional().nullable(),
    signedContractDate: any().optional().nullable(),
    createdAt: any().optional().nullable(),
    createdBy: any().optional().nullable(),
    updatedAt: any().optional().nullable(),
    updatedBy: any().optional().nullable(),
    remark: string().optional().nullable(),
    status: string().optional().nullable(),

    // UI
    joinDate: string().min(1, { message: "Offer date is required!" }),
    hireDate: string().min(1, { message: "Hire date is required!" })
});

const Offer = object({
    id: any().optional().nullable(),
    candidateId: any().optional().nullable(),
    interviewId: any().optional().nullable(),
    candidateName: string().optional().nullable(),
    applicationCode: string().optional().nullable(),
    applicationDate: any().optional().nullable(),
    applicationPrefix: string().optional().nullable(),
    applicationNumber: any().optional().nullable(),
    departmentId: number().optional().nullable(),
    departmentName: string().optional().nullable(),
    headDepartmentId: number().optional().nullable(),
    headDepartmentName: string().optional().nullable(),
    offerPositionId: number().optional().nullable(),
    offerPositionName: string().optional().nullable(),
    offerLocationId: number().optional().nullable(),
    offerLocationName: string().optional().nullable(),
    businessDivisionId: number().optional().nullable(),
    businessDivisionName: string().optional().nullable(),
    offerSalary: any().optional().nullable(),
    offerDate: any().optional().nullable(),
    offerWeek: any().optional().nullable(),
    offerMonth: any().optional().nullable(),
    submitOPSOfficeDate: any().optional().nullable(),
    submitCEOOfficeDate: any().optional().nullable(),
    receivedOPSOfficeDate: any().optional().nullable(),
    receivedCEOOfficeDate: any().optional().nullable(),
    signedOfferDate: any().optional().nullable(),
    signedContractDate: any().optional().nullable(),
    createdAt: any().optional().nullable(),
    createdBy: any().optional().nullable(),
    updatedAt: any().optional().nullable(),
    updatedBy: any().optional().nullable(),
    remark: string().optional().nullable(),
    status: string().optional().nullable(),
});

export const AssessmentModel = {
    Hire,
    Offer
};